Fix build with rust 1.80
- run `cargo update time`, fixes error:
```
error[E0282]: type annotations needed for `Box<_>`
  --> /build/lunatic-0.13.2-vendor/time-0.3.20/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API
   change in Rust 1.80.0; update `time` to version `>=0.3.35` by
   calling `cargo update`
```